version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_logistica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234   # tu contraseña real
      MYSQL_DATABASE: logistica
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_logistica
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: logistica
    volumes:
      - .:/app
    command: python app.py

volumes:
  db_data: