services:
  frontend-public:
    build:
      context: ./frontend-public
      args:
        VITE_API_URL: http://localhost:5000/api
        VITE_PRIVATE_URL: http://localhost:3001/login
    container_name: frontend_public_logistica
    depends_on:
      - backend-api
    ports:
      - "3000:80"
    networks:
      - logistica_network
    restart: unless-stopped

  frontend-private:
    build:
      context: ./frontend-private
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: frontend_private_logistica
    depends_on:
      - backend-api
    ports:
      - "3001:80"
    networks:
      - logistica_network
    restart: unless-stopped

  backend-api:
    build:
      context: ./backend-api
    container_name: backend_api_logistica
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: logistica
      JWT_SECRET: cambia_este_secreto_en_produccion
      JWT_EXPIRES_IN: 8h
      CORS_ORIGIN: http://frontend-public:80
    volumes:
      - ./logs:/logs
    networks:
      - logistica_network
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: database_logistica
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: logistica
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - logistica_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:

networks:
  logistica_network:
    driver: bridge
