services:
  db:
    image: mysql:8.0
    container_name: mysql_logistica
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: logistica
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: backend_logistica
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: logistica
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/frontend-app
    container_name: frontend_logistica
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  db_data: